book-editor.web/Controllers/CoverController.cs
using book_editor.service.CoverServices;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace book_editor.web.Controllers
{
    public class CoverController : Controller
    {
        #region ctor


        private readonly ICoverService _coverServie;
        public CoverController(ICoverService coverServie)
        {
            _coverServie = coverServie;
        }

        #endregion

        public ActionResult GetCover(int id)
        {
            var cover = _coverServie.Get(id);
            string fileType = "image/jpg";
            string fileName = "";

            if (cover == null)
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(@"~/Files/emptyCover.jpg");
                fileName = "defaultCover.jpg";
                return File(fileBytes, fileType, fileName);
            }

            byte[] mas = cover.File;
            fileName = cover.FileName;
            return File(mas, fileType, fileName);
        }

        [HttpPost]
        public int SaveCover(int bookId, HttpPostedFileBase cover)
        {
            if (!ModelState.IsValid)
            {
                return 0;
            }
            int Id = _coverServie.Save(bookId, cover);
            return Id;

        }

        [HttpPost]
        public ActionResult RemoveCover(int id)
        {
            _coverServie.Delete(id);
            return Json(true);
        }
    }
}

book-editor.web/Controllers/HomeController.cs
using book_rditor.service.BookServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace book_editor.web.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
           return View();
        }
    }
}

book-editor.web/Views/Home/Index.cshtml
<style>
    .k-edit-form-container {
        width: 620px !important;
    }

    #card > .k-input {
        width: 100% !important;
    }

    .k-grid tbody .k-button {
        min-width: 0 !important;
    }
</style>


<div id="gridBooks"></div>
<div id="fileWindow" style="display:none;">
    
    <div id="coverContainer">

    </div>
    <div style="width:100%;text-align:center">
        <img style="width:280px;height:400px" id="bigCover" />
    </div>
</div>
@section Scripts
    {
    <script>
        var bookUrl = "@Url.Action("Books", "api")";
        var authorUrl = "@Url.Action("Authors", "api")";
        var saveCoverUrl = "@Url.Action("SaveCover", "Cover")";
        var removeCoverUrl = "@Url.Action("RemoveCover", "Cover")";
        var getCoverUrl = "@Url.Action("GetCover", "Cover")";
        var defaultCover = "/Files/emptyCover.jpg";
        var maxWidth = 375;
    </script>

   
    <script type="text/x-kendo-template" id="book-editor-cover">
        <a href="\\#" data-id="#:Id#" data-is-with-cover="#:IsWithCover#" class="cover-ref">
        <img style="width:70px;height:100px" class="cover-for-book-#:Id#" src="#:IsWithCover?getCoverUrl+'/'+Id:'/Files/emptyCover.jpg'#" />
        </a>
    </script>
   
    <script type="text/x-kendo-template" id="book-editor-form">
          <div>
            <div class="k-edit-form-container" id="card">
                <div class="k-edit-label">
                    <label for="Header">Заголовок</label>
                </div>
                <div data-container-for="Header" class="k-edit-field">
                    <textarea type="text" style="width:100%;max-width:#=maxWidth#px" class="k-input k-textbox" name="Header" id="Header" required="required" validationmessage="Поле обязательное для заполнения" data-bind="value:Header"></textarea>
                </div>
                <div class="k-edit-label">
                    <label for="Header">Авторы</label>
                </div>
                <div data-container-for="authorsGridMsg" class="k-edit-field">
                    <div id="authorsGrid"></div>
                    <input class="k-input k-textbox" data-bind="value:AuctorsShort" style="display:none" name="authorsGridMsg" id="authorsGridMsg" />
                </div>
                <div class="k-edit-label">
                    <label for="PageCount">Количество страниц</label>
                </div>
                <div data-container-for="PageCount" class="k-edit-field">
                    <input type="text" style="width:100%" class="k-input" name="PageCount" id="PageCount" data-role="numerictextbox" data-bind="value:PageCount" required data-min="1" data-max="10000" validationmessage="Введите значение от 0 до 10000" />
                </div>
                <div class="k-edit-label">
                    <label for="PublishingOffice">Издательство</label>
                </div>
                <div data-container-for="PublishingOffice" class="k-edit-field">
                    <textarea type="text" style="width:100%;max-width:#=maxWidth#px" class="k-input k-textbox" name="PublishingOffice" validationmessage="Поле обязательное для заполнения" data-bind="value:PublishingOffice"></textarea>
                </div>
                <div class="k-edit-label">
                    <label for="PublishYear">Год</label>
                </div>
                <div data-container-for="PublishYear" class="k-edit-field">
                    <input data-role="numerictextbox" style="width:100%" class="k-input" data-format="n0" data-bind="value:PublishYear" data-min="1800" data-max="#:new Date().getFullYear()#" />
                </div>
                <div class="k-edit-label">
                    <label for="ISBN">ISBN</label>
                </div>
                <div data-container-for="ISBN" class="k-edit-field">
                    <input type="text" style="width:100%;max-width:#=maxWidth#px" data-role='maskedtextbox' class="k-input maskedtextbox" id="isbn" name="ISBN" data-mask="\\978-0-00-000000-0" data-bind="value:ISBN" data-validmask-msg="Не коректный ISNB " required="required" />
                    <span data-for='isbn' class='k-invalid-msg'></span>
                </div>
            </div>
        </div>
    </script>

    <script src="~/Scripts/App/fileUploadWindow.js"></script>
    <script src="~/Scripts/App/bookEditorHelp.js"></script>
    <script src="~/Scripts/App/authorTable.js"></script>
    <script src="~/Scripts/App/main.js"></script>

}